// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVFZw2pD-1JII6WL5GJ4mVpRLXoVO370',
    appId: '1:31070021746:web:22764487b499051f843aeb',
    messagingSenderId: '31070021746',
    projectId: 'nevark-stock-app',
    authDomain: 'nevark-stock-app.firebaseapp.com',
    storageBucket: 'nevark-stock-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3vMbp2sgo_oDXp9Tcdf6TSaGCJkheB_Q',
    appId: '1:31070021746:android:b277d09bccaf3463843aeb',
    messagingSenderId: '31070021746',
    projectId: 'nevark-stock-app',
    storageBucket: 'nevark-stock-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCig-aylu9egF7C1TIIAxOvEYK1J8p3js',
    appId: '1:31070021746:ios:97e3c1f37898e10a843aeb',
    messagingSenderId: '31070021746',
    projectId: 'nevark-stock-app',
    storageBucket: 'nevark-stock-app.firebasestorage.app',
    iosClientId: '31070021746-opq34i064qqnd91t04aag09ugcepls0s.apps.googleusercontent.com',
    iosBundleId: 'com.nevark.nevarkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCig-aylu9egF7C1TIIAxOvEYK1J8p3js',
    appId: '1:31070021746:ios:97e3c1f37898e10a843aeb',
    messagingSenderId: '31070021746',
    projectId: 'nevark-stock-app',
    storageBucket: 'nevark-stock-app.firebasestorage.app',
    iosClientId: '31070021746-opq34i064qqnd91t04aag09ugcepls0s.apps.googleusercontent.com',
    iosBundleId: 'com.nevark.nevarkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVFZw2pD-1JII6WL5GJ4mVpRLXoVO370',
    appId: '1:31070021746:web:7876238dc65ddd0d843aeb',
    messagingSenderId: '31070021746',
    projectId: 'nevark-stock-app',
    authDomain: 'nevark-stock-app.firebaseapp.com',
    storageBucket: 'nevark-stock-app.firebasestorage.app',
  );

}